name: CI/CD
on:
  push:

env:
  DEBUG: testcontainers:containers

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To add version tags
      packages: write # To push docker image
      issues: write   # Semantic release to link issues
    steps:
      - uses: actions/checkout@master

      - uses: homecentr/action-build-docker-image@master
        with:
          imageName: "homecentr/qbittorrent"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          dockerHubUserName: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASSWORD }}